Temos um handler que pega a exception do gRPC e mapeia para erro HttpStatus e ainda retorna com HttpResponse. Esse handler chamamos de GlobalStatusExceptionHandler. Vamos entao criar o GlobalStatusExceptionHandlerTest, para testar se o mapeamento está correto.
Vamos precisar criar a classe GlobalStatusExceptionHandlerTest;
Como a função que vamos testar tem um parâmetro do tipo HttpRequest, vamos criar um atributo na classe de teste desse tipo, para ser usado em todos os testes;
Dentro de cada função de teste vamos criar uma mensagem que informa o erro ao cliente e também um StatusRuntimeException;
Ainda dentro de cada função vamos chamar o método que faz o mapemanto, no caso handle() da classe GlobalStatusExceptionHandler e colocar a resposta em uma variavel;
Por fim verificar se a resposta do mapeamento tem o status que queriamos que tivesse.

Veja como ficou:

internal class GlobalStatusExceptionHandlerTest{

    val requestGenerica = HttpRequest.GET<Any>("/")

    @Test
    fun `deve retornar 404 quando statusException for not found`(){

        //Cenario
        val mensagem = "nao encontrado"
        val notFoundException = StatusRuntimeException(Status.NOT_FOUND.withDescription(mensagem))

        //Ação
        val resposta = GlobalStatusExceptionHandler().handle(requestGenerica, notFoundException)

        //Verfificação
        Assertions.assertEquals(HttpStatus.NOT_FOUND, resposta.status)
        Assertions.assertNotNull(resposta.body())
        Assertions.assertEquals(mensagem, (resposta.body() as JsonError).message)
    }

    @Test
    fun `deve retornar 400 quando statusException for invalid arqgument`(){

        //Cenario
        val mensagem = "Dados incorretos"
        val invalidArgumentException = StatusRuntimeException(Status.INVALID_ARGUMENT.withDescription(mensagem))

        //Ação
        val resposta = GlobalStatusExceptionHandler().handle(requestGenerica, invalidArgumentException)

        //Verfificação
        Assertions.assertEquals(HttpStatus.BAD_REQUEST, resposta.status)
    }

    @Test
    fun `deve retornar 422 quando statusException for already exist`(){

        //Cenario
        val mensagem = "Chave já cadastrada"
        val alreadyExistException = StatusRuntimeException(Status.ALREADY_EXISTS.withDescription(mensagem))

        //Ação
        val resposta = GlobalStatusExceptionHandler().handle(requestGenerica, alreadyExistException)

        //Verfificação
        Assertions.assertEquals(HttpStatus.UNPROCESSABLE_ENTITY, resposta.status)
    }

    @Test
    fun `deve retornar 500 quando ocorrer outros erros`(){

        //Cenario
        val internalException = StatusRuntimeException(Status.INTERNAL)

        //Ação
        val resposta = GlobalStatusExceptionHandler().handle(requestGenerica, internalException)

        //Verfificação
        Assertions.assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, resposta.status)
    }
}
